plugins {
    id 'fabric-loom' version '1.6.12'
}

version = project.mod_version
group = project.maven_group
base.archivesName = project.archives_base_name

loom {
    splitEnvironmentSourceSets()
    mods {
        jane {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'com.google.code.gson:gson:2.10'
    testImplementation sourceSets.client.output
}

sourceSets.test.compileClasspath += sourceSets.client.compileClasspath
sourceSets.test.runtimeClasspath += sourceSets.client.runtimeClasspath

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}

test {
    useJUnitPlatform()
    def localTemp = file("${buildDir}/tmp/jane-tests")
    doFirst { localTemp.mkdirs() }
    systemProperty 'java.io.tmpdir', localTemp.absolutePath
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
